<?php 

$marketingCards = [
    ["typeClass" => "marketing", "type" => "маркетинг", "image" => "assets/images/marketing1.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Октомври 2019", "seeMore" => "#"],
    ["typeClass" => "marketing", "type" => "маркетинг", "image" => "assets/images/marketing2.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Октомври 2019", "seeMore" => "#"],
    ["typeClass" => "marketing", "type" => "маркетинг", "image" => "assets/images/marketing3.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Октомври 2019", "seeMore" => "#"],
    ["typeClass" => "marketing", "type" => "маркетинг", "image" => "assets/images/marketing4.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Октомври 2019", "seeMore" => "#"],
    ["typeClass" => "marketing", "type" => "маркетинг", "image" => "assets/images/marketing5.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Октомври 2019", "seeMore" => "#"],
    ["typeClass" => "marketing", "type" => "маркетинг", "image" => "assets/images/marketing6.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Октомври 2019", "seeMore" => "#"]
];

$programmingCards = [
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming1.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming2.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming3.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming4.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming5.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming6.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming7.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming8.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming9.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"],
    ["typeClass" => "programming", "type" => "програмирање", "image" => "assets/images/programming10.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Април 2020", "seeMore" => "#"]
];

$designCards = [
    ["typeClass" => "design", "type" => "дизајн", "image" => "assets/images/design1.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Август 2019", "seeMore" => "#"],
    ["typeClass" => "design", "type" => "дизајн", "image" => "assets/images/design2.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Август 2019", "seeMore" => "#"],
    ["typeClass" => "design", "type" => "дизајн", "image" => "assets/images/design3.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Август 2019", "seeMore" => "#"],
    ["typeClass" => "design", "type" => "дизајн", "image" => "assets/images/design4.jpg", "headline" => "Име на проектот овде стои во две линии", "description" => "Краток опис во кој студентите ќе можат да опишат за што се работи во проектот.", "academyStart" => "Април 2019", "academyEnd" => "Август 2019", "seeMore" => "#"],
];
?>
